#Set geometry

/cell/activeLen 1 cm
/cell/cellLen 75.16 cm
/cell/wallThickness 2 mm


/run/initialize
/tracking/verbose 1


/filter/recordWhenHit cellActive

#/gps/particle   ion
#/gps/ion 19 40
#/gps/ion 92 238

/gps/particle neutron
/gps/particle geantino

#/gps/position 1000 0 0 mm
/gps/pos/type Point
/gps/pos/centre 100 0 0 cm

/gps/ang/type iso
/gps/ang/rot1 0 1 0
/gps/ang/rot2 0 0 1
/gps/ang/mintheta 0 rad
/gps/ang/maxtheta 0.1 rad

#/gps/pos/type Volume
#/gps/pos/shape Cylinder
#/gps/pos/centre 0 0 -2 cm
#/gps/pos/radius 1 mm
#/gps/pos/halfz  1 mm

#/gps/direction -1 0 0

#/gps/ene/type User
#/gps/hist/type energy
#/control/execute macros/n_yield_Unat.mac

/gps/energy 2 MeV

/run/printProgress 10000
/run/beamOn 1
