# Macro file for the initialization
# in interactive session

#Set geometry
/geometry/type 0
/geometry/dimensionFile config/geometry/dimensions_Ricochet.dat
/geometry/cryostatWallFile config/geometry/cryostatWall_Ricochet.dat
/geometry/cryoPlateFile config/geometry/cryoPlates_Ricochet.dat
/geometry/cryoBeamFile config/geometry/cryostatBeams_Ricochet.dat
#/geometry/dimensionFile config/geometry/dimensions_Nucleus.dat
#/geometry/cryostatWallFile config/geometry/cryostatWall_Nucleus.dat
#/geometry/cryoPlateFile config/geometry/cryoPlates_Nucleus.dat
#/geometry/cryoBeamFile config/geometry/cryostatBeams_Nucleus.dat

# Set some default verbose
/control/verbose 2
/control/saveHistory
/run/verbose 2
#
# Change the default number of threads (in multi-threaded mode)
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
# Visualization setting
/control/execute vis.mac
